version: '1.9'

services:
  web:
    build:
      dockerfile: Dockerfile
    image: docker-test:1.0
    ports:
      - 8082:8082
    healthcheck:
      test: ["CMD","curl" ,"-f", "http://localhost:8082/product"]
      interval: 10s
      timeout: 100s
      retries: 5

  postman:
    image: postman/newman:alpine
    container_name: postmanTests
    depends_on:
      web:
        condition: service_healthy
    command:
      run postman_collection.json -e postman_environment.json --insecure
    volumes:
      - C:/Users/xncandir/Desktop/demo:/etc/newman
    network_mode: "host"








